apiVersion: v1
kind: ReplicationController
metadata:
  name: "rc1"

spec:
  replicas: 5
  selector:
    app: web
  template:
    metadata:
      name: "skpod2"
      labels:
        app: web

    spec:
      containers:
      - name: "container2"
        image: "vimal13/apache-webserver-php"